#line 2 "mysql.yy.c"

#line 4 "mysql.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 129
#define YY_END_OF_BUFFER 130
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[442] =
    {   0,
        0,    0,  130,  128,    1,    2,  128,  128,  120,  128,
      124,  125,  118,  116,  122,  117,  126,  119,  104,  123,
      112,  109,  114,  127,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  128,  128,  128,
        1,  111,    0,  108,    0,  107,    3,  105,    0,  106,
      104,  113,  110,  115,  100,  100,  100,  100,    8,  100,
      100,  100,  100,  100,   36,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,   55,   51,  100,  100,  100,

      100,  100,  100,  100,  100,  100,  100,  100,   33,   10,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,    0,
        0,  121,  102,    0,    3,    0,    0,  105,   46,   42,
      100,    9,   39,  100,   87,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,   62,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,   63,
      100,   76,  100,   92,  100,  100,  100,   89,   88,  100,
       11,   96,  100,  100,  100,  100,  100,  100,  100,  100,

      100,  100,  100,   24,  100,   86,  100,  100,  100,  100,
       50,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      103,  101,    4,  100,  100,  100,   74,   70,   58,   65,
      100,  100,  100,  100,  100,  100,  100,  100,   71,  100,
      100,  100,   40,  100,  100,   13,   61,  100,  100,  100,
      100,    6,   30,  100,  100,  100,  100,  100,  100,  100,
       21,   26,   28,  100,   53,  100,  100,  100,  100,   52,
      100,  100,  100,  100,  100,   68,  100,  100,  100,  100,
      100,  100,   66,   60,   72,   94,  100,  100,  100,  100,
      100,  100,  100,   19,   59,  100,   14,  100,  100,  100,

       80,  100,  100,   85,  100,   32,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,   68,  100,   35,  100,
       54,   18,   27,  100,  100,  100,  100,   48,   91,  100,
      100,  100,  100,   38,   31,  100,  100,   29,  100,  100,
      100,   15,  100,   43,  100,  100,   90,   34,  100,  100,
        7,  100,  100,  100,   84,   95,   12,  100,  100,  100,
      100,  100,   25,  100,   69,   45,   57,  100,   37,   20,
      100,  100,   92,   47,  100,  100,   49,  100,  100,   17,
        5,   93,  100,   79,   23,   22,  100,  100,   56,   70,
      100,  100,  100,   67,   81,  100,   77,   63,  100,  100,

       67,   75,  100,  100,  100,   64,  100,  100,   16,   73,
       41,  100,   83,  100,  100,  100,  100,  100,  100,   44,
      100,   93,   73,  100,  100,  100,   78,  100,  100,  100,
      100,   97,   98,  100,  100,   82,  100,  100,  100,   99,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,   21,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,    1,   49,    1,   50,   51,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
       76,   47,    1,   77,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[78] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    4,    3,
        5,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1
    } ;

static const flex_int16_t yy_base[450] =
    {   0,
        0,    0,  831,  869,  828,  869,  809,  822,  869,  818,
      869,  869,  869,  869,  869,  811,  805,  809,   64,  869,
       62,  869,  796,  869,   58,   53,   66,   81,   59,  103,
       45,   63,  111,   60,   71,  122,  127,  117,  129,   71,
        0,  135,  166,  217,  162,  155,  114,    0,    0,  737,
      810,  869,  806,  803,  799,  798,    0,  322,  235,  207,
      146,  869,  869,  869,    0,  129,  163,  145,  156,  162,
      177,  165,  175,  176,    0,  174,  199,  195,  214,  179,
      178,  235,  184,  189,  216,  217,  238,  241,  228,  227,
      236,  241,  242,  236,  251,  272,    0,  254,  239,  264,

      256,  256,  258,  271,  285,  275,  289,  290,    0,  299,
      284,  296,  312,  300,  302,  318,  334,  309,  290,  315,
      310,  308,  318,  320,  335,  333,  334,  340,  344,  168,
      165,  869,  208,  204,    0,  157,  367,  139,    0,    0,
      350,    0,    0,  343,    0,  339,  361,  352,  360,  349,
      367,  350,  370,  360,  377,  361,  365,  385,  375,  386,
      384,  388,  376,  396,  383,  397,    0,  400,  387,  406,
      404,  398,  400,  394,  409,  411,  418,  419,  420,  425,
      413,    0,  411,  426,  429,  429,  438,    0,    0,  435,
       62,    0,  434,  442,  430,  445,  446,  443,  446,  454,

      454,  460,  461,    0,  448,    0,  457,  451,  458,  470,
        0,  465,  467,  482,  480,  473,  469,  488,  470,  480,
      869,  869,  869,  482,   56,  498,    0,  499,    0,    0,
      495,  494,  508,  490,  491,  497,  513,  517,  502,  512,
      505,  507,    0,  520,  519,    0,    0,  516,  515,  518,
      533,    0,    0,  527,  530,  540,  523,  532,  533,  546,
        0,    0,    0,  534,    0,  538,  542,  557,  552,    0,
      549,  564,  552,  553,  575,    0,  560,  559,  569,  582,
      566,  582,    0,    0,  570,    0,  577,  571,  575,  580,
      595,  598,  596,    0,    0,  600,    0,  598,  605,  610,

        0,  599,  594,    0,  613,    0,  606,  622,  615,  625,
      615,  624,  616,  626,  616,  619,    0,  632,    0,  635,
        0,    0,    0,  625,  641,  628,  641,    0,    0,  626,
      631,  646,  638,    0,    0,  644,  658,    0,  663,  645,
      649,    0,  650,    0,  666,  668,    0,    0,  655,  677,
        0,  666,  669,  670,    0,    0,    0,  666,  668,  676,
      678,  671,    0,  693,    0,    0,    0,  684,    0,    0,
      681,  697,    0,    0,  693,  703,    0,  682,  695,    0,
        0,  702,  711,    0,    0,    0,  697,  715,    0,    0,
       40,  717,  718,    0,    0,  704,    0,    0,  722,  715,

        0,    0,  727,  717,  720,    0,  716,  736,    0,    0,
        0,  718,    0,  738,  737,  730,  742,  748,  741,    0,
      732,    0,    0,  745,  739,  749,    0,  760,  761,  762,
      755,    0,  752,  752,  755,    0,  777,  769,  767,    0,
      869,  834,  839,   84,  844,  849,  853,  858,  863
    } ;

static const flex_int16_t yy_def[450] =
    {   0,
      441,    1,  441,  441,  441,  441,  441,  442,  441,  443,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  445,  446,  441,
      441,  441,  442,  441,  443,  441,  447,  441,  448,  441,
      441,  441,  441,  441,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  445,
      446,  441,  441,  449,  447,  448,  448,  441,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      441,  441,  441,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,
        0,  441,  441,  441,  441,  441,  441,  441,  441
    } ;

static const flex_int16_t yy_nxt[947] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   41,   41,   41,   48,    4,   41,
       49,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   41,   41,   50,   60,   72,   61,
       62,   63,   66,   93,   94,   73,   65,   76,   74,  408,
       67,   86,   68,   87,   77,   98,   99,   69,   75,   70,

       71,   78,   81,   88,   79,  298,   82,   80,   72,  112,
       83,  269,   66,   93,   94,   73,   84,   76,   74,   85,
       67,   86,   68,   87,   77,   98,   99,   69,   75,   70,
       71,   78,   81,   88,   79,   89,   82,   80,   90,  112,
       83,   91,  129,   95,   92,   96,   84,  100,  103,   85,
       97,  101,  106,  139,  138,  108,  104,  102,  107,   60,
      113,   61,  105,  109,  114,   89,  137,  110,   90,  142,
      111,   91,  129,   95,   92,   96,  127,  100,  103,  143,
       97,  101,  106,  139,  128,  108,  104,  102,  107,  115,
      113,  116,  105,  109,  114,  140,  124,  110,  125,  142,

      111,  126,  144,  141,  145,  146,  127,  117,   54,  143,
      147,  148,  134,  149,  128,  222,  221,  157,  158,  115,
      150,  116,  138,  163,  151,  140,  124,  152,  125,  153,
      164,  126,  144,  141,  145,  146,  154,  117,  118,  155,
      147,  148,  119,  149,  137,  120,  121,  157,  158,  156,
      150,  165,  122,  163,  151,  123,  166,  152,  159,  153,
      164,  160,  167,  170,  168,  171,  154,  161,  118,  155,
      169,  172,  119,  173,  162,  120,  121,  174,  175,  156,
      176,  165,  122,  181,  182,  123,  166,  185,  159,  186,
      183,  160,  167,  170,  168,  171,  177,  161,  184,  187,

      169,  172,  188,  173,  162,  189,  178,  174,  175,  190,
      176,  179,  180,  181,  182,  191,  195,  185,  192,  186,
      183,  193,  194,  196,  197,  198,  177,  201,  184,  187,
      202,  207,  188,  199,  208,  189,  178,   58,  200,  190,
      209,  179,  180,  210,  211,  191,  195,  212,  192,  213,
      203,  193,  194,  196,  197,  198,  205,  201,  204,  214,
      202,  207,  216,  199,  208,  219,  217,  206,  200,  220,
      209,  215,  218,  210,  211,  224,  137,  212,  225,  213,
      203,  223,  226,  227,  228,  229,  205,  230,  204,  214,
      231,  232,  216,  233,  234,  219,  217,  206,  235,  220,

      236,  215,  218,  237,  240,  224,  238,  241,  225,  242,
      239,  243,  226,  227,  228,  229,  244,  230,  245,  246,
      231,  232,  247,  233,  234,  248,  249,  250,  235,  251,
      236,  252,  253,  237,  240,  254,  238,  241,  255,  242,
      239,  243,  256,  257,  258,  259,  244,  262,  245,  246,
      260,  263,  247,  264,  265,  248,  249,  250,  266,  251,
      261,  252,  253,  267,  268,  254,  270,  271,  255,  272,
      273,  274,  256,  257,  258,  259,  275,  262,  276,  277,
      260,  263,  278,  264,  265,  279,  280,  281,  266,  282,
      261,  283,  284,  267,  268,  285,  270,  271,  286,  272,

      273,  274,  287,  289,  288,  290,  275,  291,  276,  277,
      292,  293,  278,  294,  295,  279,  280,  281,  296,  282,
      297,  283,  284,  299,  300,  285,  301,  302,  286,  303,
      304,  305,  287,  289,  288,  290,  306,  291,  307,  308,
      292,  293,  309,  294,  295,  310,  311,  312,  296,  313,
      297,  314,  315,  299,  300,  316,  301,  302,  317,  303,
      304,  305,  318,  319,  320,  321,  306,  322,  307,  308,
      323,  324,  309,  325,  327,  310,  311,  312,  328,  313,
      329,  314,  315,  330,  326,  316,  331,  332,  317,  333,
      334,  335,  318,  319,  320,  321,  336,  322,  337,  338,

      323,  324,  339,  325,  327,  340,  341,  342,  328,  343,
      329,  344,  345,  330,  326,  346,  331,  332,  347,  333,
      334,  335,  348,  349,  350,  351,  336,  352,  337,  338,
      353,  354,  339,  355,  356,  340,  341,  342,  357,  343,
      358,  344,  345,  359,  360,  346,  361,  362,  347,  363,
      364,  365,  348,  349,  350,  351,  366,  352,  367,  368,
      353,  354,  369,  355,  356,  370,  371,  372,  357,  373,
      358,  374,  375,  359,  360,  376,  361,  362,  377,  363,
      364,  365,  378,  379,  380,  381,  366,  382,  367,  368,
      383,  384,  369,  385,  386,  370,  371,  372,  387,  373,

      388,  374,  375,  389,  390,  376,  391,  392,  377,  393,
      394,  395,  378,  379,  380,  381,  396,  382,  397,  398,
      383,  384,  399,  385,  386,  400,  401,  402,  387,  403,
      388,  404,  405,  389,  390,  406,  391,  392,  407,  393,
      394,  395,  409,  410,  411,  412,  396,  413,  397,  398,
      414,  415,  399,  416,  417,  400,  401,  402,  420,  403,
      418,  404,  405,  421,  422,  406,  423,  424,  407,  425,
      426,  427,  409,  410,  411,  412,  419,  413,  428,  429,
      414,  415,  430,  416,  417,  431,  432,  433,  420,  434,
      418,  435,  436,  421,  422,  437,  423,  424,  438,  425,

      426,  427,  439,  440,   55,   56,  419,  134,  428,  429,
      133,   51,  430,  132,   64,  431,  432,  433,   59,  434,
       58,  435,  436,   57,   56,  437,   54,   52,  438,   51,
      441,  441,  439,  440,   53,   53,   53,   53,   53,   55,
       55,   55,   55,   55,  130,  130,  130,  441,  130,  131,
      131,  131,  131,  135,  441,  135,  135,  135,  136,  136,
      136,  136,  136,  134,  134,  134,  134,  134,    3,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,

      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441
    } ;

static const flex_int16_t yy_chk[947] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   19,   26,   19,
       21,   21,   25,   31,   32,   26,  444,   27,   26,  391,
       25,   29,   25,   29,   27,   34,   35,   25,   26,   25,

       25,   27,   28,   29,   27,  225,   28,   27,   26,   40,
       28,  191,   25,   31,   32,   26,   28,   27,   26,   28,
       25,   29,   25,   29,   27,   34,   35,   25,   26,   25,
       25,   27,   28,   29,   27,   30,   28,   27,   30,   40,
       28,   30,   47,   33,   30,   33,   28,   36,   37,   28,
       33,   36,   38,   66,  138,   39,   37,   36,   38,   61,
       42,   61,   37,   39,   42,   30,  136,   39,   30,   68,
       39,   30,   47,   33,   30,   33,   46,   36,   37,   69,
       33,   36,   38,   66,   46,   39,   37,   36,   38,   43,
       42,   43,   37,   39,   42,   67,   45,   39,   45,   68,

       39,   45,   70,   67,   71,   72,   46,   43,  134,   69,
       73,   74,  133,   76,   46,  131,  130,   80,   81,   43,
       77,   43,   60,   83,   77,   67,   45,   78,   45,   78,
       84,   45,   70,   67,   71,   72,   78,   43,   44,   79,
       73,   74,   44,   76,   59,   44,   44,   80,   81,   79,
       77,   85,   44,   83,   77,   44,   86,   78,   82,   78,
       84,   82,   87,   89,   88,   90,   78,   82,   44,   79,
       88,   91,   44,   92,   82,   44,   44,   93,   94,   79,
       95,   85,   44,   98,   99,   44,   86,  101,   82,  101,
      100,   82,   87,   89,   88,   90,   96,   82,  100,  102,

       88,   91,  103,   92,   82,  104,   96,   93,   94,  105,
       95,   96,   96,   98,   99,  106,  108,  101,  106,  101,
      100,  107,  107,  110,  111,  112,   96,  114,  100,  102,
      115,  118,  103,  113,  119,  104,   96,   58,  113,  105,
      120,   96,   96,  121,  122,  106,  108,  123,  106,  124,
      116,  107,  107,  110,  111,  112,  117,  114,  116,  125,
      115,  118,  126,  113,  119,  128,  127,  117,  113,  129,
      120,  125,  127,  121,  122,  141,  137,  123,  144,  124,
      116,  137,  146,  147,  148,  149,  117,  150,  116,  125,
      151,  152,  126,  153,  154,  128,  127,  117,  155,  129,

      156,  125,  127,  157,  159,  141,  158,  160,  144,  161,
      158,  162,  146,  147,  148,  149,  163,  150,  164,  165,
      151,  152,  166,  153,  154,  168,  169,  170,  155,  171,
      156,  172,  173,  157,  159,  174,  158,  160,  175,  161,
      158,  162,  176,  177,  178,  179,  163,  181,  164,  165,
      180,  183,  166,  184,  185,  168,  169,  170,  186,  171,
      180,  172,  173,  187,  190,  174,  193,  194,  175,  195,
      196,  197,  176,  177,  178,  179,  198,  181,  199,  200,
      180,  183,  201,  184,  185,  202,  203,  205,  186,  207,
      180,  208,  209,  187,  190,  210,  193,  194,  212,  195,

      196,  197,  213,  214,  213,  215,  198,  216,  199,  200,
      217,  218,  201,  219,  220,  202,  203,  205,  220,  207,
      224,  208,  209,  226,  228,  210,  231,  232,  212,  233,
      234,  235,  213,  214,  213,  215,  236,  216,  237,  238,
      217,  218,  239,  219,  220,  240,  241,  242,  220,  244,
      224,  245,  248,  226,  228,  249,  231,  232,  250,  233,
      234,  235,  251,  254,  255,  256,  236,  257,  237,  238,
      258,  259,  239,  260,  264,  240,  241,  242,  266,  244,
      267,  245,  248,  268,  260,  249,  269,  271,  250,  272,
      273,  274,  251,  254,  255,  256,  275,  257,  277,  278,

      258,  259,  279,  260,  264,  280,  281,  282,  266,  285,
      267,  287,  288,  268,  260,  289,  269,  271,  290,  272,
      273,  274,  291,  292,  293,  296,  275,  298,  277,  278,
      299,  300,  279,  302,  303,  280,  281,  282,  305,  285,
      307,  287,  288,  308,  309,  289,  310,  311,  290,  312,
      313,  314,  291,  292,  293,  296,  315,  298,  316,  318,
      299,  300,  320,  302,  303,  324,  325,  326,  305,  327,
      307,  330,  331,  308,  309,  332,  310,  311,  333,  312,
      313,  314,  336,  337,  339,  340,  315,  341,  316,  318,
      343,  345,  320,  346,  349,  324,  325,  326,  350,  327,

      352,  330,  331,  353,  354,  332,  358,  359,  333,  360,
      361,  362,  336,  337,  339,  340,  364,  341,  368,  371,
      343,  345,  372,  346,  349,  375,  376,  378,  350,  379,
      352,  382,  383,  353,  354,  387,  358,  359,  388,  360,
      361,  362,  392,  393,  396,  399,  364,  400,  368,  371,
      403,  404,  372,  405,  407,  375,  376,  378,  412,  379,
      408,  382,  383,  414,  415,  387,  416,  417,  388,  418,
      419,  421,  392,  393,  396,  399,  408,  400,  424,  425,
      403,  404,  426,  405,  407,  428,  429,  430,  412,  431,
      408,  433,  434,  414,  415,  435,  416,  417,  437,  418,

      419,  421,  438,  439,   56,   55,  408,   54,  424,  425,
       53,   51,  426,   50,   23,  428,  429,  430,   18,  431,
       17,  433,  434,   16,   10,  435,    8,    7,  437,    5,
        3,    0,  438,  439,  442,  442,  442,  442,  442,  443,
      443,  443,  443,  443,  445,  445,  445,    0,  445,  446,
      446,  446,  446,  447,    0,  447,  447,  447,  448,  448,
      448,  448,  448,  449,  449,  449,  449,  449,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,

      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grammars/mysql.l"
#line 2 "grammars/mysql.l"
#include "mysql.tab.h"
#include "AST.h"
#include <string>
#include <cstring>
#include <iostream>

int currLine = 1;
int currCol = 1;

// Global error state
std::string syntaxError;
int errorLine = -1;
int errorColumn = -1;

// Setter function to report errors
void setSyntaxError(const std::string& msg, int line, int col) {
    syntaxError = msg;
    errorLine = line;
    errorColumn = col;
}

// Getters (so SyntaxAnalyzer.cpp can use them)
std::string getSyntaxError() { return syntaxError; }
int getErrorLine() { return errorLine; }
int getErrorColumn() { return errorColumn; }

// Buffer for query string input
std::string inputBuffer;
size_t inputIndex = 0;

void setInputString(const std::string& input) {
    inputBuffer = input;
    inputIndex = 0;
    currLine = 1;
    currCol = 1;
    // Clear previous error state
    syntaxError = "";
    errorLine = -1;
    errorColumn = -1;
}

// Custom input function for Flex
#define YY_INPUT(buf,result,max_size) \
    { \
        if (inputIndex >= inputBuffer.size()) { \
            result = YY_NULL; \
        } else { \
            size_t n = std::min((size_t)max_size, inputBuffer.size() - inputIndex); \
            memcpy(buf, inputBuffer.c_str() + inputIndex, n); \
            inputIndex += n; \
            result = n; \
            for (size_t i = 0; i < n; i++) { \
                if (buf[i] == '\n') { currLine++; currCol = 1; } \
                else currCol++; \
            } \
        } \
    }
#line 860 "mysql.yy.c"
#define YY_NO_INPUT 1
#line 862 "mysql.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 63 "grammars/mysql.l"


#line 1080 "mysql.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 442 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 869 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 65 "grammars/mysql.l"
{ /* skip whitespace */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 66 "grammars/mysql.l"
{ currLine++; currCol = 1; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 67 "grammars/mysql.l"
{ /* skip SQL comments */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 68 "grammars/mysql.l"
{ /* skip C-style comments */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 70 "grammars/mysql.l"
{ return SELECT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 71 "grammars/mysql.l"
{ return FROM; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 72 "grammars/mysql.l"
{ return WHERE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 73 "grammars/mysql.l"
{ return AS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 74 "grammars/mysql.l"
{ return AND; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 75 "grammars/mysql.l"
{ return OR; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 76 "grammars/mysql.l"
{ return NOT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 77 "grammars/mysql.l"
{ return CREATE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 78 "grammars/mysql.l"
{ return DROP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 79 "grammars/mysql.l"
{ return ALTER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 80 "grammars/mysql.l"
{ return TABLE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 81 "grammars/mysql.l"
{ return DATABASE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "grammars/mysql.l"
{ return SCHEMA; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 83 "grammars/mysql.l"
{ return INDEX; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "grammars/mysql.l"
{ return VIEW; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 85 "grammars/mysql.l"
{ return INSERT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "grammars/mysql.l"
{ return INTO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 87 "grammars/mysql.l"
{ return VALUES; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 88 "grammars/mysql.l"
{ return UPDATE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 89 "grammars/mysql.l"
{ return SET; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "grammars/mysql.l"
{ return DELETE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "grammars/mysql.l"
{ return JOIN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 93 "grammars/mysql.l"
{ return INNER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 94 "grammars/mysql.l"
{ return LEFT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 95 "grammars/mysql.l"
{ return RIGHT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "grammars/mysql.l"
{ return FULL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "grammars/mysql.l"
{ return OUTER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 98 "grammars/mysql.l"
{ return CROSS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "grammars/mysql.l"
{ return ON; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "grammars/mysql.l"
{ return USING; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 102 "grammars/mysql.l"
{ return GROUP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 103 "grammars/mysql.l"
{ return BY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 104 "grammars/mysql.l"
{ return HAVING; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 105 "grammars/mysql.l"
{ return ORDER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "grammars/mysql.l"
{ return ASC; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "grammars/mysql.l"
{ return DESC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 108 "grammars/mysql.l"
{ return DISTINCT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "grammars/mysql.l"
{ return ALL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 111 "grammars/mysql.l"
{ return UNION; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 112 "grammars/mysql.l"
{ return INTERSECT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 113 "grammars/mysql.l"
{ return EXCEPT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 114 "grammars/mysql.l"
{ return ADD; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 115 "grammars/mysql.l"
{ return MODIFY; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 117 "grammars/mysql.l"
{ return LIMIT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 118 "grammars/mysql.l"
{ return OFFSET; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 119 "grammars/mysql.l"
{ return TOP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 121 "grammars/mysql.l"
{ return IS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 122 "grammars/mysql.l"
{ return NULLSYM; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 123 "grammars/mysql.l"
{ return LIKE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 124 "grammars/mysql.l"
{ return ILIKE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 125 "grammars/mysql.l"
{ return IN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 126 "grammars/mysql.l"
{ return BETWEEN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 127 "grammars/mysql.l"
{ return EXISTS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 128 "grammars/mysql.l"
{ return CASE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 129 "grammars/mysql.l"
{ return WHEN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 130 "grammars/mysql.l"
{ return THEN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 131 "grammars/mysql.l"
{ return ELSE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "grammars/mysql.l"
{ return END; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 134 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 135 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 136 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 137 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 138 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 139 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 140 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 141 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 142 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 143 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 144 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 145 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DATATYPE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 147 "grammars/mysql.l"
{ return PRIMARY; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 148 "grammars/mysql.l"
{ return KEY; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 149 "grammars/mysql.l"
{ return FOREIGN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 150 "grammars/mysql.l"
{ return REFERENCES; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 151 "grammars/mysql.l"
{ return UNIQUE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 152 "grammars/mysql.l"
{ return CHECK; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 153 "grammars/mysql.l"
{ return DEFAULT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 154 "grammars/mysql.l"
{ return AUTO_INCREMENT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 155 "grammars/mysql.l"
{ return NOT_NULL; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 156 "grammars/mysql.l"
{ return COLUMN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 158 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 159 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 160 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 161 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 162 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 163 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 164 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 165 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 166 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 167 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 168 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 169 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 170 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 171 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 172 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FUNCTION; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 173 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 174 "grammars/mysql.l"
{ 
                                // Remove backticks and store the identifier
                                std::string temp(yytext + 1);
                                temp.pop_back();
                                yylval.strVal = strdup(temp.c_str());
                                return IDENTIFIER; 
                            }
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 181 "grammars/mysql.l"
{ 
                                // Remove quotes and store the identifier
                                std::string temp(yytext + 1);
                                temp.pop_back();
                                yylval.strVal = strdup(temp.c_str());
                                return IDENTIFIER; 
                            }
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 188 "grammars/mysql.l"
{ 
                                // Remove brackets and store the identifier
                                std::string temp(yytext + 1);
                                temp.pop_back();
                                yylval.strVal = strdup(temp.c_str());
                                return IDENTIFIER; 
                            }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 196 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return INTVAL; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 197 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FLOATVAL; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 198 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return FLOATVAL; }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 200 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return STRINGVAL; }
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 201 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return STRINGVAL; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 203 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return EQ; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 204 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return NE; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 205 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return NE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 206 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return LT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 207 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return LE; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 208 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return GT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 209 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return GE; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 210 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return PLUS; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 211 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return MINUS; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 212 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return ASTERISK; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 213 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return DIVIDE; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 214 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return MODULO; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 215 "grammars/mysql.l"
{ yylval.strVal = strdup(yytext); return CONCAT_OP; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 218 "grammars/mysql.l"
{ return COMMA; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 219 "grammars/mysql.l"
{ return SEMICOLON; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 220 "grammars/mysql.l"
{ return LPAREN; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 221 "grammars/mysql.l"
{ return RPAREN; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 222 "grammars/mysql.l"
{ return DOT; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 223 "grammars/mysql.l"
{ return QUESTION; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 225 "grammars/mysql.l"
{
                                // Invalid token
                                std::string msg = "Unexpected token: ";
                                msg += yytext;
                                setSyntaxError(msg, currLine, currCol);
                                return yytext[0];
                            }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 233 "grammars/mysql.l"
ECHO;
	YY_BREAK
#line 1813 "mysql.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 442 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 442 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 441);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 233 "grammars/mysql.l"

